'use strict';

/**
 * Manifest Updater — updates dashboard/catalogs/{clientId}-manifest.json
 * after a repository analysis run.
 *
 * Rules:
 *   - Creates the manifest file if it does not exist
 *   - Merges new features into existing manifest (does not overwrite existing entries)
 *   - Updates lastUpdated, repositoryCommit, repositoryBranch, catalogVersion
 *   - Existing feature entries with status !== 'Discovered' are preserved as-is
 *     (except sourceFiles and lastAnalyzed which are always refreshed)
 */

const fs   = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', '..');

/**
 * Update the catalog manifest for a client.
 *
 * @param {string}   clientId
 * @param {object[]} features      - Scored RawFeature array (with .confidence)
 * @param {object}   repoContext   - From repo-resolver
 * @param {object[]} writtenItems  - From catalog-writer (catalogDir per feature)
 * @param {object}   logger
 */
async function updateManifest(clientId, features, repoContext, writtenItems, logger) {
  logger.section('Updating Catalog Manifest');

  const manifestPath = path.join(ROOT, 'dashboard', 'catalogs', `${clientId}-manifest.json`);

  // Load or initialise manifest
  let manifest = await _loadManifest(manifestPath, clientId, logger);

  const now = new Date().toISOString();

  // Update top-level metadata
  manifest.clientId         = clientId;
  manifest.lastUpdated      = now;
  manifest.catalogVersion   = _bumpVersion(manifest.catalogVersion || '0.0.0');
  manifest.repositoryCommit = repoContext.currentCommit;
  manifest.repositoryBranch = repoContext.branch;
  manifest.featuresCount    = features.length;

  if (!manifest.features) manifest.features = {};

  // Merge features
  let added   = 0;
  let updated = 0;

  for (const feature of features) {
    const writtenItem = (writtenItems || []).find(w => w.featureId === feature.featureId);
    const existing    = manifest.features[feature.featureId];

    if (existing && existing.status && existing.status !== 'Discovered') {
      // Preserve manually progressed entries — only refresh paths and timestamp
      existing.lastAnalyzed    = now;
      existing.confidence      = feature.confidence;
      existing.catalogPath     = writtenItem?.catalogDir || existing.catalogPath || '';
      updated++;
    } else {
      // New or rescan of a Discovered feature
      manifest.features[feature.featureId] = {
        featureId:     feature.featureId,
        module:        feature.module,
        displayName:   _toDisplayName(feature.featureName),
        status:        existing?.status || 'Discovered',
        confidence:    feature.confidence,
        discoveredAt:  existing?.discoveredAt || now,
        lastAnalyzed:  now,
        catalogPath:   writtenItem?.catalogDir || '',
        specPath:      `tests/playwright/clients/${clientId}/specs/${feature.module.toLowerCase()}/feature-${feature.featureKebab}/`,
        coverage: {
          functional:  0,
          validation:  0,
          workflow:    0,
          database:    0,
          security:    0,
        },
        implementationStatus: {
          smoke:        { implemented: false, lastUpdated: null },
          regression:   { implemented: false, lastUpdated: null },
          e2e:          { implemented: false, lastUpdated: null },
          functionalUnit: { implemented: false, lastUpdated: null },
        },
      };
      added++;
    }
  }

  // Write manifest
  await fs.promises.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.promises.writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');

  logger.info(`Manifest updated: ${added} added, ${updated} refreshed`);
  logger.info(`Manifest path: ${path.relative(ROOT, manifestPath).replace(/\\/g, '/')}`);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function _loadManifest(manifestPath, clientId, logger) {
  if (!fs.existsSync(manifestPath)) {
    logger.warn('Manifest file not found — creating new manifest.');
    return {
      _readme:  'Auto-generated by Repository Analysis Pipeline.',
      clientId,
      features: {},
    };
  }

  try {
    const raw = await fs.promises.readFile(manifestPath, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    logger.warn(`Could not parse manifest (${err.message}) — starting fresh.`);
    return {
      _readme:  'Auto-generated by Repository Analysis Pipeline.',
      clientId,
      features: {},
    };
  }
}

function _bumpVersion(version) {
  const parts = String(version).split('.').map(Number);
  while (parts.length < 3) parts.push(0);
  parts[2]++;
  return parts.join('.');
}

function _toDisplayName(name) {
  return name
    .replace(/[-_]+/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\b\w/g, c => c.toUpperCase());
}

module.exports = { updateManifest };
